name: PHPStan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  php-matrix:
    name: PHP matrix
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.php-matrix.outputs.versions }}
    steps:
      - uses: actions/checkout@v5

      - uses: typisttech/php-matrix-action@v3
        id: php-matrix

  phpstan:
    name: PHPStan (PHP ${{ matrix.php }})
    needs: php-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJSON(needs.php-matrix.outputs.versions) }}
    steps:
      - uses: actions/checkout@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      - uses: ramsey/composer-install@v3

      - run: composer stan
